title: Baseball Analytics Blog
description: Learn baseball analytics with SAS and historic figures
author: Sam Edgemon
theme: jekyll-theme-cayman
show_edit_link: false

show_downloads: false
github:
  is_project_page: false




include:
  - assets/css/custom.css



