title: Baseball Analytics Blog
description: Learn baseball analytics with SAS and historic figures
author: Sam Edgemon
theme: jekyll-theme-minimal
show_edit_link: false

# Custom navigation (youâ€™ll call this in your layout)
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Contact"
    url: /contact

include:
  - assets/css/custom.css



