title: The Sports Analytics Series
description: Explore the world of data and analytics through your favorite sports.
author: Sam Edgemon
theme: jekyll-theme-cayman
show_edit_link: false

show_downloads: false
github:
  is_project_page: false

  # Navigation links
nav:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact




include:
  - assets/css/custom.css



